name: Release Package Version
on:
  push:  
    tags:
     - v*     
jobs: 
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:    

    - name: Print Tag Ref
      run: echo $GITHUB_REF

    - name: Extract Version Number
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref }}
        regex: '([0-9.]+(?:[-{1}](?:[a-zA-Z])+)*)'

    - name: Print Version Number
      run: echo '${{ steps.regex-match.outputs.match }}'

    - uses: actions/checkout@v2
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./StepStack/StepStack.csproj

    - name: Build
      run: dotnet build ./StepStack/StepStack.csproj

    - name: Pack
      run: dotnet pack ./StepStack/StepStack.csproj -p:PackageVersion='${{ steps.regex-match.outputs.match }}' --output packages
      
    - name: Ls
      run: ls

    - name: Publish Package
      run: nuget push **\*.nupkg -NoSymbols -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: EzSpecflow.StepStack-v${{ steps.regex-match.outputs.match }}
        path: packages/
